[package]

name = "alltext"
version = "0.0.3"
authors = [ "Stanislav Pankevich <s.pankevich@gmail.com>" ]

[[bin]]
name = "alltext"
path = "src/alltext.rs"
test = false

[dev-dependencies]
# tempdir = "*"

